#!/usr/bin/env bash
#
# OSKAR / ROCm node check.
#
# Run this on the AMD node from the top of the extracted source tree:
#
#     bash rocm/check_node.sh 2>&1 | tee node_report.txt
#
# It surveys the ROCm environment, builds OSKAR, runs the unit tests, runs an
# end-to-end simulation, and compares the result against reference
# visibilities generated by a verified CUDA build.
#
# Backend selection:
#     BACKEND=hip   HIP build, for AMD GPUs.
#     BACKEND=cpu   (default) CPU-only build, for checking the toolchain,
#                   the dependencies and the reference data independently of
#                   any GPU.
#
# Other knobs:
#     JOBS=<n>          parallel build jobs        (default: nproc)
#     BUILD_DIR=<path>  build directory            (default: build-$BACKEND)
#     GPU_ARCH=<gfx>    override offload arch      (default: auto-detected)

set -uo pipefail

BACKEND="${BACKEND:-cpu}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 4)}"
BUILD_DIR="${BUILD_DIR:-build-$BACKEND}"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GOLDEN="$SRC_DIR/rocm/golden"

# ROCm is often installed under /opt/rocm-<version> without being added to
# PATH or LD_LIBRARY_PATH, in which case rocminfo fails with a loader error
# rather than anything informative. Set it up first.
if [ -z "${ROCM_PATH:-}" ]; then
    for cand in /opt/rocm /opt/rocm-*; do
        [ -d "$cand" ] && ROCM_PATH="$cand"
    done
fi
if [ -n "${ROCM_PATH:-}" ] && [ -d "$ROCM_PATH" ]; then
    export ROCM_PATH
    export HIP_PATH="${HIP_PATH:-$ROCM_PATH}"
    export PATH="$ROCM_PATH/bin:$PATH"
    export LD_LIBRARY_PATH="$ROCM_PATH/lib:$ROCM_PATH/lib64:${LD_LIBRARY_PATH:-}"
fi

# A cmake installed by rocm/bootstrap_cmake.sh. It lives outside the source
# tree so that replacing the source does not delete it.
OSKAR_TOOLCHAIN_DIR="${OSKAR_TOOLCHAIN_DIR:-$HOME/.local/oskar-cmake}"
export OSKAR_TOOLCHAIN_DIR
[ -x "$OSKAR_TOOLCHAIN_DIR/bin/cmake" ] && export PATH="$OSKAR_TOOLCHAIN_DIR/bin:$PATH"

pass=0
fail=0

rule()    { printf '\n%s\n' "===============================================================================" ; }
section() { rule; printf '== %s\n' "$1"; rule; }
ok()      { printf '  [ OK ]   %s\n' "$1"; pass=$((pass+1)); }
bad()     { printf '  [FAIL]   %s\n' "$1"; fail=$((fail+1)); }
info()    { printf '  %s\n' "$1"; }

# -----------------------------------------------------------------------------
section "1. Environment"
# -----------------------------------------------------------------------------
info "host      : $(hostname 2>/dev/null || echo unknown)"
info "kernel    : $(uname -sr)"
info "distro    : $(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME" || echo unknown)"
info "cores     : $(nproc 2>/dev/null || echo '?')"
CMAKE_BIN=""
for c in cmake cmake3; do
    command -v "$c" >/dev/null 2>&1 && { CMAKE_BIN="$c"; break; }
done
if [ -n "$CMAKE_BIN" ]; then
    info "cmake     : $($CMAKE_BIN --version | head -1)  [$CMAKE_BIN]"
else
    info "cmake     : NOT FOUND -- run 'bash rocm/bootstrap_cmake.sh' first"
fi
info "compiler  : $(${CXX:-c++} --version 2>/dev/null | head -1 || echo 'NOT FOUND')"
info "python3   : $(python3 --version 2>&1 || echo 'NOT FOUND')"

echo
echo "--- ROCm toolchain ---"
for t in hipcc hipconfig rocminfo rocm-smi amd-smi rocprofv3; do
    p="$(command -v "$t" 2>/dev/null)"
    if [ -n "$p" ]; then info "$(printf '%-10s: %s' "$t" "$p")"; else info "$(printf '%-10s: not found' "$t")"; fi
done

echo
echo "--- hipconfig --full ---"
hipconfig --full 2>&1 | head -40 || echo "(hipconfig unavailable)"

echo
echo "--- rocm-smi (the nvidia-smi equivalent) ---"
if command -v rocm-smi >/dev/null 2>&1; then
    rocm-smi 2>&1 | head -30
elif command -v amd-smi >/dev/null 2>&1; then
    amd-smi monitor 2>&1 | head -30
else
    echo "(neither rocm-smi nor amd-smi found)"
fi

echo
echo "--- GPU agents, wavefront size and LDS (this drives the port design) ---"
ROCMINFO_OUT=""
if command -v rocminfo >/dev/null 2>&1; then
    # stderr is captured, not discarded: when rocminfo produces nothing the
    # reason is almost always here (missing libhsa on the loader path, or no
    # permission on /dev/kfd), and that same failure would break every HIP
    # program on the node.
    ROCMINFO_OUT="$(rocminfo 2>&1)"
    if [ -z "$ROCMINFO_OUT" ]; then
        echo "(rocminfo produced no output at all)"
    else
        echo "$ROCMINFO_OUT" | grep -iE "(Name|Marketing Name|Device Type|Compute Unit|Wavefront Size|Workgroup Max Size|LDS|Chip|gfx)" | head -50
        if ! echo "$ROCMINFO_OUT" | grep -q "gfx"; then
            echo
            echo "  !! rocminfo named no GPU agent. Raw output follows:"
            echo "$ROCMINFO_OUT" | head -25 | sed 's/^/     /'
            echo "  !! If this is a permission error, check membership of the"
            echo "  !! 'video' and 'render' groups: id -nG"
            id -nG 2>/dev/null | sed 's/^/     groups: /'
            ls -l /dev/kfd 2>&1 | sed 's/^/     /'
        fi
    fi
else
    echo "(rocminfo not found)"
fi

DETECTED_ARCH="$(echo "$ROCMINFO_OUT" | grep -oE 'gfx[0-9a-f]+' | head -1)"
WAVEFRONT="$(echo "$ROCMINFO_OUT" | grep -i 'Wavefront Size' | head -1 | grep -oE '[0-9]+' | head -1)"
GPU_ARCH="${GPU_ARCH:-$DETECTED_ARCH}"
echo
info "detected arch      : ${GPU_ARCH:-<none>}"
info "detected wavefront : ${WAVEFRONT:-<unknown>}"
if [ "${WAVEFRONT:-}" = "64" ]; then
    info ">> wave64: the correlation kernel's 32-lane tiling is correct but"
    info ">> splits each wavefront across two baselines. Performance concern."
elif [ "${WAVEFRONT:-}" = "32" ]; then
    info ">> wave32: lane geometry matches the CUDA assumptions exactly."
fi

# -----------------------------------------------------------------------------
section "2. Optional dependencies"
# -----------------------------------------------------------------------------
probe_lib() {
    local name="$1"; shift
    local hit=""
    for pat in "$@"; do
        hit="$(find $pat -maxdepth 3 2>/dev/null | head -1)"
        [ -n "$hit" ] && break
    done
    if [ -n "$hit" ]; then info "$(printf '%-10s: %s' "$name" "$hit")"
    else info "$(printf '%-10s: absent -- optional, build proceeds without it' "$name")"; fi
}
probe_lib casacore /usr/include/casacore /usr/local/include/casacore
probe_lib hdf5 "/usr/lib64/libhdf5*.so*" "/usr/lib/x86_64-linux-gnu/libhdf5*.so*"
for lib in rocfft hipfft rocblas; do
    f="$(find /opt/rocm* -name "lib${lib}*.so*" 2>/dev/null | head -1)"
    if [ -n "$f" ]; then info "$(printf '%-10s: %s' "$lib" "$f")"; else info "$(printf '%-10s: not found' "$lib")"; fi
done

# -----------------------------------------------------------------------------
section "3. Configure and build  (BACKEND=$BACKEND)"
# -----------------------------------------------------------------------------
CMAKE_ARGS=( -DCMAKE_BUILD_TYPE=Release
             -DCMAKE_INSTALL_PREFIX="$SRC_DIR/$BUILD_DIR/install" )
case "$BACKEND" in
    cpu)
        # Explicitly off, so a stray CUDA or OpenCL install cannot change what
        # is being measured.
        CMAKE_ARGS+=( -DFIND_CUDA=OFF -DFIND_OPENCL=OFF )
        ;;
    hip)
        CMAKE_ARGS+=( -DFIND_CUDA=OFF -DFIND_OPENCL=OFF -DFIND_HIP=ON )
        CMAKE_ARGS+=( -DCMAKE_PREFIX_PATH="${ROCM_PATH:-/opt/rocm}" )
        CMAKE_ARGS+=( -DCMAKE_HIP_COMPILER="${ROCM_PATH:-/opt/rocm}/llvm/bin/clang++" )
        [ -n "${GPU_ARCH:-}" ] && CMAKE_ARGS+=( -DHIP_ARCH="$GPU_ARCH" )
        ;;
    *)
        bad "unknown BACKEND '$BACKEND' (expected cpu or hip)"; exit 1 ;;
esac

# Compiling for gfx90a needs no GPU access, but running does. Say so before
# the build rather than after a confusing runtime failure.
if [ "$BACKEND" = "hip" ] && [ -e /dev/kfd ] && [ ! -r /dev/kfd ]; then
    info ""
    info ">> /dev/kfd is not readable by this account, so no HIP program can"
    info ">> run here regardless of whether it builds. Ask an administrator"
    info ">> to add you to the 'video' and 'render' groups:"
    info ">>     sudo usermod -aG video,render $(id -un)"
    info ">> The build below will still tell us whether the port compiles."
    info ""
fi

info "cmake args: ${CMAKE_ARGS[*]}"
rm -rf "$SRC_DIR/$BUILD_DIR"
mkdir -p "$SRC_DIR/$BUILD_DIR"
cd "$SRC_DIR/$BUILD_DIR" || exit 1

if [ -z "$CMAKE_BIN" ]; then
    info "no cmake found -- bootstrapping one now"
    if bash "$SRC_DIR/rocm/bootstrap_cmake.sh" 2>&1 | sed 's/^/         /'; then
        export PATH="$OSKAR_TOOLCHAIN_DIR/bin:$PATH"
        hash -r 2>/dev/null || true
        for c in cmake cmake3; do
            command -v "$c" >/dev/null 2>&1 && { CMAKE_BIN="$c"; break; }
        done
    fi
fi
if [ -z "$CMAKE_BIN" ]; then
    bad "still no cmake -- bootstrap failed above. It needs either outbound"
    bad "network access or rocm/cmake-3.28.6-linux-x86_64.tar.gz staged by hand."
    exit 1
fi
info "using cmake: $($CMAKE_BIN --version | head -1)"
if "$CMAKE_BIN" .. "${CMAKE_ARGS[@]}" > cmake.log 2>&1; then
    ok "cmake configure"
    grep -iE "WARNING|not found|NOT found" cmake.log | head -12 | sed 's/^/         /'
else
    bad "cmake configure -- last 30 lines:"
    tail -30 cmake.log | sed 's/^/         /'
    exit 1
fi

if make -k -j"$JOBS" > build.log 2>&1; then
    ok "build ($JOBS jobs)"
    # Collect the applications, libraries and headers in one prefix, which is
    # what anyone using OSKAR from outside the build tree will want.
    if make install > install.log 2>&1; then
        ok "installed into $SRC_DIR/$BUILD_DIR/install"
    else
        info "install step failed (the build itself is fine; nothing below"
        info "needs the installed copy):"
        tail -5 install.log | sed 's/^/         /'
    fi
else
    bad "build failed"
    # A parallel build interleaves diagnostics from several compilers, which
    # shreds multi-line clang errors into unreadable soup. Rebuild serially to
    # get clean, ordered output -- it only has to compile what is left.
    # -k on both passes: stopping at the first failing translation unit hid
    # eleven of twelve failures in an earlier round.
    info "re-running serially for readable diagnostics..."
    make -k -j1 > build_serial.log 2>&1
    info "failing translation units:"
    grep -oE "\*\*\* \[[^]]*\.o\]" build_serial.log | sed 's/.*CMakeFiles\/[^/]*\.dir\///; s/\.o\]$//' \
        | sort -u | sed 's/^/         /'
    echo
    LOG=build_serial.log
    [ -s "$LOG" ] || LOG=build.log

    echo
    info "distinct error messages, by frequency:"
    grep -oE "error: .*" "$LOG" | sed 's/[0-9]\+/N/g' | sort | uniq -c \
        | sort -rn | head -15 | sed 's/^/         /'
    echo
    info "first failing translation unit, in full:"
    awk '/error:/{found=1} found{print; n++} n>40{exit}' "$LOG" \
        | head -40 | sed 's/^/         /'
    echo
    info "full logs kept at $PWD/build.log and $PWD/build_serial.log"
    exit 1
fi

# -----------------------------------------------------------------------------
section "4. Device detection by OSKAR itself"
# -----------------------------------------------------------------------------
./apps/oskar_system_info 2>&1 | head -45

# -----------------------------------------------------------------------------
section "5. Unit tests"
# -----------------------------------------------------------------------------
CTEST_BIN="$(command -v "${CMAKE_BIN}" >/dev/null 2>&1 && dirname "$(command -v "$CMAKE_BIN")" || echo)"
if [ -n "$CTEST_BIN" ] && [ -x "$CTEST_BIN/ctest" ]; then CTEST_BIN="$CTEST_BIN/ctest"; else CTEST_BIN="ctest"; fi
if "$CTEST_BIN" --output-on-failure > ctest.log 2>&1; then
    ok "ctest: $(grep -oE '[0-9]+% tests passed.*' ctest.log | head -1)"
else
    # The FEKO/HDF5 element-pattern tests assert success unconditionally
    # instead of skipping, so they fail on any build without HDF5. That is an
    # upstream test-suite gap, not a backend problem, and it must not be
    # allowed to mask a real regression -- so it is recognised specifically
    # and only when it is the *only* thing that failed.
    n_failed="$(grep -cE '^\s*[0-9]+/[0-9]+ Test .*\*\*\*Failed' ctest.log)"
    only_telescope="$(grep -E '^\s*[0-9]+/[0-9]+ Test .*\*\*\*Failed' ctest.log \
        | grep -vc 'telescope_test')"
    if grep -q "compiled without HDF5 support" ctest.log && \
            [ "$n_failed" = "1" ] && [ "$only_telescope" = "0" ]; then
        ok "ctest: only the known HDF5 element-pattern tests failed (HDF5 absent)"
        info "       these assert success rather than skipping; install HDF5"
        info "       development headers on this node to clear them"
    else
        bad "ctest failures:"
        grep -E "\*\*\*|Failed|tests passed" ctest.log | head -25 | sed 's/^/         /'
        # A bare "Failed" is not actionable; the log already holds each
        # failing case's assertion and error figures.
        echo
        info "failing test cases and what they asserted:"
        grep -E "^\[  FAILED  \]|Failure$|Value of:|Actual:|Expected:|Which is:|RELATIVE ERROR|ERROR:" ctest.log \
            | grep -v "tests, listed below" | grep -v "compiled without HDF5 support" \
            | head -60 | sed 's/^/         /'
    fi
fi
grep -E "^\s*[0-9]+/[0-9]+ Test" ctest.log | sed 's/^/  /'

# -----------------------------------------------------------------------------
section "6. End-to-end simulation vs golden reference"
# -----------------------------------------------------------------------------
WORK="$SRC_DIR/$BUILD_DIR/e2e"
rm -rf "$WORK"; mkdir -p "$WORK"; cd "$WORK" || exit 1
cp -r "$GOLDEN/telescope.tm" "$GOLDEN/sky.txt" "$GOLDEN/bench.ini" . 2>/dev/null

SIM="$SRC_DIR/$BUILD_DIR/apps/oskar_sim_interferometer"
CMP="$SRC_DIR/$BUILD_DIR/apps/oskar_vis_compare"

for prec in double single; do
    ini="run_$prec.ini"
    cp bench.ini "$ini"
    if [ "$prec" = "single" ]; then
        sed -i 's/double_precision=true/double_precision=false/' "$ini"
    fi
    sed -i "s|oskar_vis_filename=.*|oskar_vis_filename=out_$prec.vis|" "$ini"
    [ "$BACKEND" = "cpu" ] && sed -i '/^\[simulator\]/a use_gpus=false' "$ini"

    echo
    echo "--- $prec precision ---"
    t0=$(date +%s.%N)
    if "$SIM" "$ini" > "sim_$prec.log" 2>&1; then
        t1=$(date +%s.%N)
        wall=$(awk "BEGIN{printf \"%.2f\", $t1-$t0}")
        rep=$(grep -E "Total wall time" "sim_$prec.log" | tr -s ' ')
        ok "simulation completed in ${wall}s  (${rep:-no internal timing})"
        grep -E "Compute\s+:|Jones E|Jones correlate|Device" "sim_$prec.log" | head -8 | sed 's/^/         /'
    else
        bad "simulation failed -- last 15 lines:"
        tail -15 "sim_$prec.log" | sed 's/^/         /'
        continue
    fi

    if "$CMP" "$GOLDEN/golden_$prec.vis" "out_$prec.vis" 2>&1 | sed 's/^/         /'; then
        ok "$prec precision matches the golden reference"
    else
        bad "$prec precision DIFFERS from the golden reference"
    fi
done

# -----------------------------------------------------------------------------
if [ "$BACKEND" = "hip" ]; then
section "7. Confirm the first-use fix"
# -----------------------------------------------------------------------------
# On ROCm 6.1 with gfx90a, the first kernel in a process could read wrong
# values from buffers just filled from the host. HIP builds clear every new
# allocation to avoid it (see rocm/README.md). This runs the test that exposed
# the problem with the workaround on and off, so a future ROCm version can be
# checked against it in one line.
T="$SRC_DIR/$BUILD_DIR/oskar/correlate/test/correlate_test"
F="auto_correlate.matrix_singleGPU_doubleGPU"
for envset in "" "OSKAR_HIP_NO_CLEAR_ON_ALLOC=1"; do
    result="$(env ${envset} "$T" --gtest_filter="$F" 2>&1 \
        | grep -E "^\[ *(OK|FAILED) *\] auto|RELATIVE ERROR" | head -2 | tr '\n' ' ')"
    printf '  %-50s %s\n' "${envset:-fix on (default)}" "$result"
done
fi

# -----------------------------------------------------------------------------
section "Summary"
# -----------------------------------------------------------------------------
info "backend        : $BACKEND"
info "gpu arch       : ${GPU_ARCH:-<none detected>}"
info "wavefront size : ${WAVEFRONT:-<unknown>}"
info "checks passed  : $pass"
info "checks failed  : $fail"
rule
if [ "$fail" -eq 0 ]; then
    echo "ALL CHECKS PASSED"
else
    echo "$fail CHECK(S) FAILED -- paste this whole report back"
fi
rule
exit "$fail"
